debug: false

logging:
  path: /Users/mawic/Downloads/log


spring:
  datasource:
    url: jdbc:mysql://95.163.202.32:3306/repair?characterEncoding=utf-8
    username: root
    password:

  jackson:
    serialization:
      fail_on_empty_beans: false
