debug: false

logging:
  path: /Users/mawic/Downloads/log


spring:
  datasource:
#    url: jdbc:mysql://95.163.202.32:3306/repair?characterEncoding=utf-8
#    username: root
#    password:
    url: jdbc:mysql://47.101.39.28:3306/repair_prod?characterEncoding=utf-8&useSSL=false
    username: root
    password: repair@2018

  jackson:
    serialization:
      fail_on_empty_beans: false
